[project]
name = "mvc"
version = "2025.0.0"
dependencies = [
    "fastapi[standard]",
    "pydantic",
    "psycopg",
    "psycopg2-binary",
    "yoyo-migrations",
    "python-dotenv",
    "datetime",
    "pytest"
]

[tool.hatch.envs.default.scripts]
migrate = "yoyo apply"
start = "fastapi dev main.py"